name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install node
        uses: actions/setup-node@v4
      - name: Install npm dependencies
        run: npm ci
      - name: Compile typescript
        run: npm run build
      - name: Check for diffs
        run: git diff --no-ext-diff --exit-code
      - name: Install browser for Playwright
        run: npx playwright install --with-deps chromium
      - name: Run tests
        run: npm run test
