name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      - name: Install npm dependencies
        run: npm ci
      - name: Compile typescript
        run: npm run build
      - name: Check for diffs
        run: git diff --no-ext-diff --exit-code
      - name: Install browser for Playwright
        run: npx playwright install --with-deps chromium
      - name: Run tests
        run: npm run test
